### ISSUE TITLE
zsh: command not found: git_info_for_prompt

### ISSUE THREAD

**Issue by nop33** [OmeGak/dotfiles#30]
In the file `zsh/config.zsh` the command `git_info_for_prompt` is referenced, but it doesn't exist anywhere in the project.
I found this out after a clean install. When the `make` command finished and I opened a new terminal window, I got the error message:
```
zsh: command not found: git_info_for_prompt
```

**Comment by OmeGak** [comment]
I'm not sure, but I think that's a Git built-in. It probably has something to do with your PATH. I just checked in my system and doing 

```console
$ echo $(git_info_for_prompt)
zsh: command not found: git_info_for_prompt
``` 

However, if I print `PS1`, I can see that `git_info_for_prompt` got resolved when sourcing `config.zsh`.

```console
$ echo ${PS1}
$(username): $(directory_name) $(git_dirty)$(need_push)
›
``` 

I would need to debug and see why it resolves to `$(git_dirty)$(need_push)`.

**Comment by nop33** [comment]
The the hint from https://github.com/zplug/zplug/issues/409#issuecomment-310199321 I managed to solve the problem by replacing
```
pinstall brew zplug
```
with
```
git clone https://github.com/zplug/zplug ~/.zplug
```
in `.dot/zsh/install.dep.sh`
and
```
export ZPLUG=$BREWDIR/opt/zplug
```
with
```
export ZPLUG=$HOME/.zplug
```
in `.dot/zsh/zshenv.symlink`
Don't ask me why.
